mysite/blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('search/', views.search, name='search'),
    path('usercomments/', views.UserCommentListView.as_view(), name='usercomments'),
    path('userposts/', views.UserPostListView.as_view(), name='userposts'),
    path('', views.PostListView.as_view(), name="posts"),
    path('<int:pk>', views.PostDetailView.as_view(), name='post'),
    path('posts/new/', views.PostCreateView.as_view(), name="post_new"),
    path('posts/<int:pk>/delete/', views.PostDeleteView.as_view(), name="post_delete"),
    path('posts/<int:pk>/update/', views.PostUpdateView.as_view(), name="post_update"),
    path('posts/<int:post_id>/commentdelete/<int:pk>/', views.CommentDeleteView.as_view(), name="comment_delete"),
    path('posts/<int:post_id>/commentedit/<int:pk>/', views.CommentUpdateView.as_view(), name="comment_edit"),
    path('posts/usercommentdelete/<int:pk>/', views.UserCommentDeleteView.as_view(), name="usercomment_delete"),
    path('posts/usercommentedit/<int:pk>/', views.UserCommentUpdateView.as_view(), name="usercomment_edit"),
    path('profile/', views.profile, name='profile'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static, settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
] + (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from PIL import Image as PIL_Image

# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name="Pavadinimas", max_length=100)
    content = HTMLField(verbose_name="Tekstas", max_length=8000)
    created = models.DateTimeField(verbose_name="Sukūrimo data", auto_now_add=True)
    user = models.ForeignKey(to=User, verbose_name="Autorius", on_delete=models.SET_NULL, null=True)


    def num_comments(self):
        return self.comments.count()

    class Meta:
        ordering = ["-created"]

class Comment(models.Model):
    content = models.TextField(verbose_name="Tekstas", max_length=1000)
    created = models.DateTimeField(verbose_name="Sukūrimo data", auto_now_add=True)
    post = models.ForeignKey(to="Post", verbose_name="Įrašas", on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(to=User, verbose_name="Autorius", on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ["-created"]

class Image(models.Model):
    photo = models.ImageField(verbose_name="Nuotrauka", upload_to="post_photos", null=True, blank=True)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="profile_pics/default.png", upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profile"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = PIL_Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

mysite/blog/forms.py
from .models import Comment, Profile
from django import forms
from django.contrib.auth.models import User

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

mysite/blog/views.py
from django.shortcuts import render, reverse, redirect
from django.views import generic
from .models import Post, Comment
from django.views.generic.edit import FormMixin
from .forms import CommentForm, UserUpdateForm, ProfileUpdateForm
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.forms import User
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# Create your views here.

@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Vartotojo vardas {username} užimtas!')
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Vartotojas su el. paštu {email} jau užregistruotas!')
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, f'Vartotojas {username} užregistruotas!')
                    return redirect('login')
        else:
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('register')
    else:
        return render(request, 'registration/register.html')


from django.db.models import Q


def search(request):
    query = request.GET.get('query')
    search_results = Post.objects.filter(Q(title__icontains=query) | Q(content__icontains=query))
    return render(request, 'search.html', {'posts': search_results, 'query': query})


class UserCommentListView(LoginRequiredMixin, generic.ListView):
    model = Comment
    context_object_name = "comments"
    template_name = "usercomments.html"

    def get_queryset(self):
        return Comment.objects.filter(user=self.request.user)


class PostListView(generic.ListView):
    model = Post
    context_object_name = "posts"
    template_name = "posts.html"
    paginate_by = 5


class UserPostListView(LoginRequiredMixin, generic.ListView):
    model = Post
    context_object_name = "posts"
    template_name = "userposts.html"
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user)


class PostDetailView(FormMixin, generic.DetailView):
    model = Post
    context_object_name = 'post'
    template_name = "post.html"
    form_class = CommentForm

    def get_success_url(self):
        return reverse('post', kwargs={'pk': self.object.id})

    # standartinis post metodo perrašymas, naudojant FormMixin, galite kopijuoti tiesiai į savo projektą.
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = self.object
        form.save()
        return super().form_valid(form)


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Post
    template_name = "post_form.html"
    success_url = "/"
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Post
    success_url = "/"
    template_name = "post_delete.html"
    context_object_name = 'post'

    def test_func(self):
        return self.get_object().user == self.request.user


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Post
    template_name = "post_form.html"
    fields = ['title', 'content']
    context_object_name = 'post'

    def get_success_url(self):
        return reverse('post', kwargs={"pk": self.kwargs['pk']})

    def test_func(self):
        return self.get_object().user == self.request.user

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Comment
    # success_url = "/"
    template_name = "comment_delete.html"
    context_object_name = 'comment'

    def get_success_url(self):
        return reverse('post', kwargs={"pk": self.kwargs['post_id']})

    def test_func(self):
        return self.get_object().user == self.request.user


class UserCommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Comment
    template_name = "comment_delete.html"
    context_object_name = 'comment'

    def get_success_url(self):
        return reverse("usercomments")

    def test_func(self):
        return self.get_object().user == self.request.user


class UserCommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Comment
    template_name = "comment_edit.html"
    context_object_name = 'comment'
    fields = ['content']

    def get_success_url(self):
        return reverse("usercomments")

    def test_func(self):
        return self.get_object().user == self.request.user

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = self.get_object().post
        form.save()
        return super().form_valid(form)

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Comment
    template_name = "comment_edit.html"
    context_object_name = 'comment'
    fields = ['content']

    def get_success_url(self):
        return reverse('post', kwargs={"pk": self.kwargs['post_id']})

    def test_func(self):
        return self.get_object().user == self.request.user

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = Post.objects.get(pk=self.kwargs['post_id'])
        form.save()
        return super().form_valid(form)


def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Profilis atnaujintas")
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profile.html', context)

mysite/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block "title" %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.tiny.cloud/1/nxc8e2kwaduvatzyy3fc3wwlderx6cw0ihij2jxkpmtw53su/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow">
    <div class="container">
        <a class="navbar-brand" href="">
            <svg class="bi bi-pen" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
                 xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                      d="M5.707 13.707a1 1 0 0 1-.39.242l-3 1a1 1 0 0 1-1.266-1.265l1-3a1 1 0 0 1 .242-.391L10.086 2.5a2 2 0 0 1 2.828 0l.586.586a2 2 0 0 1 0 2.828l-7.793 7.793zM3 11l7.793-7.793a1 1 0 0 1 1.414 0l.586.586a1 1 0 0 1 0 1.414L5 13l-3 1 1-3z"/>
                <path fill-rule="evenodd"
                      d="M9.854 2.56a.5.5 0 0 0-.708 0L5.854 5.855a.5.5 0 0 1-.708-.708L8.44 1.854a1.5 1.5 0 0 1 2.122 0l.293.292a.5.5 0 0 1-.707.708l-.293-.293z"/>
                <path d="M13.293 1.207a1 1 0 0 1 1.414 0l.03.03a1 1 0 0 1 .03 1.383L13.5 4 12 2.5l1.293-1.293z"/>
            </svg>
            Mano tinklaraštis</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts' %}">Pradžia</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}">
                    <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z"
                              clip-rule="evenodd"/>
                    </svg>
                    {{ user.get_username }}</a></li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userposts' %}">Mano įrašai</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'usercomments' %}">Mano komentarai</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'post_new' %}">Naujas įrašas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Atsijungti</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Registruotis</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Prisijungti</a>
                </li>
                {% endif %}
                <li>
                    <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
                        <input name="query" class="form-control" type="text" placeholder="Paieška">
                    </form>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'info' %}success{% endif %}"
         role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
</div>

<div class="container">
    {% block "content" %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

</body>
</html>

mysite/blog/templates/comment_delete.html
{% extends "base.html" %}
{% block "title" %}Mano tinklaraštis: Komentaro trynimas{% endblock %}
{% load crispy_forms_tags %}
{% block "content" %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Ištrinti komentarą</legend>
            <h2>Ar tikrai norite ištrinti komentarą „{{ comment.content }}“?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Taip, ištrinti</button>
            <a class="btn btn-outline-secondary" href="{% url 'post' comment.post.id %}">Atšaukti</a>
        </div>
    </form>
    </div>
{% endblock %}

mysite/blog/templates/comment_edit.html
{% extends "base.html" %}
{% block "title" %}Mano tinklaraštis: Komentaro redagavimas{% endblock %}
{% load crispy_forms_tags %}
{% block "content" %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Komentaro redagavimas</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Išsaugoti</button>
        </div>
    </form>
</div>
{% endblock %}

mysite/blog/templates/post.html
{% extends "base.html" %}

{% block "title" %}Mano tinklaraštis: Straipsnis{% endblock %}

{% block "content" %}

<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2">{{ post.user }}</a>
            <img class="rounded-circle" style="width:2%"  src="{{ post.user.profile.image.url }}">
            <small class="text-muted">{{ post.created|date:"Y-m-d, f" }}</small>
            <h2><a class="article-title">{{ post.title }}</a></h2>
            {% if post.user == user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post_update' post.id %}">Redaguoti</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post_delete' post.id %}">Ištrinti</a>
            </div>
            {% endif %}
            <p class="article-content">{{ post.content|safe }}</p>
            <a>Komentarų: {{ post.num_comments }}</a>
        </div>
        <hr>
        {% if user.is_authenticated %}
        <div class="fieldWrapper">
            <br/>
            <h4>Palikite komentarą:</h4>
            <form action="" method="post">
                {% csrf_token %}
                {{ form.content }}</br>
                <input type="submit" value="Komentuoti">
            </form>
        </div>
        {% endif %}
        <h4>Komentarai:</h4>
        {% for comment in post.comments.all %}
        <small class="text-muted">{{ comment.user }}
            <img class="rounded-circle" style="width:2%"  src="{{ comment.user.profile.image.url }}">
            , {{ comment.created|date:"Y-m-d, f" }}</small>
        <p>{{ comment.content|safe }}</p>
            {% if comment.user == user %}
            <div>
                <a class="btn btn-secondary btn-sm mb-2" href="{% url 'comment_edit' post.id comment.id %}">Redaguoti</a>
                <a class="btn btn-danger btn-sm mb-2" href="{% url 'comment_delete' post.id comment.id %}">Ištrinti</a>
            </div>
            {% endif %}
        {% endfor %}
    </div>
</article>

{% endblock %}

mysite/blog/templates/post_delete.html
{% extends "base.html" %}
{% block "title" %}Mano tinklaraštis: Straipsnio trynimas{% endblock %}
{% load crispy_forms_tags %}
{% block "content" %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Ištrinti įrašą</legend>
            <h2>Ar tikrai norite ištrinti įrašą „{{ post.title }}“?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Taip, ištrinti</button>
            <a class="btn btn-outline-secondary" href="{% url 'post' post.id %}">Atšaukti</a>
        </div>
    </form>
    </div>
{% endblock %}

mysite/blog/templates/post_form.html
{% extends "base.html" %}
{% block "title" %}Mano tinklaraštis: Straipsnio kūrimas/redagavimas{% endblock %}
{% load crispy_forms_tags %}
{% block "content" %}
<div class="content-section">
    <form method="POST">
        <script>
            tinymce.init({
                selector: '#id_content',
                plugins : 'advlist autolink link image lists charmap print preview code',
                toolbar1: ' fullscreen preview bold italic underline | fontselect, fontsizeselect  | forecolor backcolor | alignleft alignright | aligncenter alignjustify | indent outdent | bullist numlist table | link image media | codesample | code |',
            });
        </script>
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Straipsnio kūrimas/redagavimas</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Išsaugoti</button>
        </div>
    </form>
</div>
{% endblock %}

mysite/blog/templates/posts.html
{% extends "base.html" %}

{% block "title" %}Mano tinklaraštis: Straipsniai{% endblock %}

{% block "content" %}

{% for post in posts %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2">{{ post.user }}</a>
            <img class="rounded-circle" style="width:2%"  src="{{ post.user.profile.image.url }}">
            <small class="text-muted">{{ post.created|date:"Y-m-d, f" }}</small>
            <h2><a class="article-title">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content|truncatewords:"30"|safe}}</p>
            <p class="card-text"><a href="{{ post.pk }}">Skaityti daugiau</a></p>
            <a>Komentarų: {{ post.num_comments }}</a>
        </div>
        <hr>
    </div>
</article>
{% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

mysite/blog/templates/profile.html
{% extends "base.html" %}
{% block "content" %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
        {% load crispy_forms_tags %}
      <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profilio info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Atnaujinti</button>
            </div>
        </form>
    </div>
{% endblock %}

mysite/blog/templates/search.html
{% extends "base.html" %}

{% block "content" %}
  <h1>Paieškos pagal "{{query}}" rezultatai:</h1>
  </br>
  {% if posts %}
  <ul>
    {% for post in posts %}
      <li>
        <a href="{% url 'post' post.id %}">{{ post.title }}</a> ({{post.user}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Oops. Nieko neradome :(</p>
  {% endif %}

  {% endblock %}

mysite/blog/templates/usercomments.html
{% extends "base.html" %}

{% block "title" %}Mano tinklaraštis: Mano komentarai{% endblock %}

{% block "content" %}

<article class="media content-section">
    <div class="media-body">
        <h1>Komentarai:</h1>
        {% for comment in comments %}
        <small class="text-muted">Straipsnis: {{ comment.post.title }} </small>
        <br>
        <small class="text-muted">{{ comment.user }}, {{ comment.created|date:"Y-m-d, f" }}</small>
        <p>{{ comment.content|safe }}</p>
        <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'usercomment_edit' comment.id %}">Redaguoti</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'usercomment_delete' comment.id %}">Ištrinti</a>
        </div>
        <hr>
        {% endfor %}
    </div>
</article>

{% endblock %}

mysite/blog/templates/userposts.html
{% extends "base.html" %}

{% block "title" %}Mano tinklaraštis: Vartotojo straipsniai{% endblock %}

{% block "content" %}

{% for post in posts %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2">{{ post.user }}</a>
            <img class="rounded-circle" style="width:2%"  src="{{ post.user.profile.image.url }}">
            <small class="text-muted">{{ post.created|date:"Y-m-d, f" }}</small>
            <h2><a class="article-title">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content|truncatewords:"30"|safe}}</p>
            <p class="card-text"><a href="{% url 'post' post.pk %}">Skaityti daugiau</a></p>
            <a>Komentarų: {{ post.num_comments }}</a>
        </div>
        <hr>
    </div>
</article>
{% endfor %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}